/**
 * Type declarations for bankflow-core-wasm
 *
 * This module is generated by wasm-pack from crates/bankflow-core.
 * The actual module is at src/lib/wasm/bankflow-core-wasm/
 */

declare module '$lib/wasm/bankflow-core-wasm/bankflow_core.js' {
  export default function init(): Promise<void>;

  export function analyze(
    fileABytes: Uint8Array,
    fileAName: string,
    fileBBytes: Uint8Array,
    fileBName: string,
    settings: string
  ): string;

  export function export_excel(
    fileABytes: Uint8Array,
    fileAName: string,
    fileBBytes: Uint8Array,
    fileBName: string,
    settings: string
  ): Uint8Array;
}
