/**
 * Type declarations for bankflow-core-wasm
 *
 * This module will be generated by wasm-pack from crates/bankflow-core.
 * Until then, these declarations allow TypeScript to compile.
 */

declare module 'bankflow-core-wasm' {
  export default function init(): Promise<void>;

  export function analyze(
    fileABytes: Uint8Array,
    fileAName: string,
    fileBBytes: Uint8Array,
    fileBName: string,
    settings: string
  ): string;

  export function export_excel(
    fileABytes: Uint8Array,
    fileAName: string,
    fileBBytes: Uint8Array,
    fileBName: string,
    settings: string
  ): Uint8Array;
}
